services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/StocksApi/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=clean-architecture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
 
  evently.redis:
    image: redis:latest
    container_name: Evently.Redis
    restart: always
    ports:
      - 6379:6379
